# Generated by Django 5.2.8 on 2026-02-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='my_users',
        ),
    ]
