# Generated by Django 5.2.8 on 2026-02-23 14:29

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_customuser_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', django.db.models.functions.datetime.Now())), name='birth_date_not_future'),
        ),
    ]
