# Generated by Django 5.2.8 on 2026-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
